forta-network/forta-node

config/containers.go
services/publisher/publisher.go
services/supervisor/start.go
services/supervisor/start_test.go

- Adds IPFS container locally to avoid doing a remote webrequest on only_hash=true lookup for CID calculations

Add ipfs node for hash calculation

---

clients/docker.go

From `675f79cc08e57ffadb875f8fa4cd3a6762885374` (v0.5.0):
```
panic: runtime error: slice bounds out of range [-1:]
goroutine 88 [running]:
github.com/forta-network/forta-node/clients.(*dockerClient).GetContainerLogs(0xc000032140, 0x13f2ca0, 0xc00078e240, 0xc011b7eb80, 0x40, 0x1156253, 0x2, 0x2710, 0xc01549d800, 0x1625, ...)
/go/app/clients/docker.go:715 +0x3fa
github.com/forta-network/forta-node/services/supervisor.(*SupervisorService).doSyncAgentLogs(0xc0000d6a00, 0x0, 0x0)
/go/app/services/supervisor/agent_logs.go:53 +0x37e
github.com/forta-network/forta-node/services/supervisor.(*SupervisorService).syncAgentLogs(0xc0000d6a00)
/go/app/services/supervisor/agent_logs.go:24 +0xaa
created by github.com/forta-network/forta-node/services/supervisor.(*SupervisorService).start …
```

Fix rare panic in bot log formatting

---

config/config.go
services/inspector/inspector.go
services/supervisor/start.go
services/supervisor/start_agent.go

@stevenlanders this runs an inspection at startup, blocks scanner deployment until the inspection is done

Run inspection at startup

---

go.mod
go.sum

This upgrades `forta-core-go` which includes decreasing the trace_block timeout to 1 minute.

Decrease trace_block timeout

---

config/config.go
store/registry.go

This lets one add bot IDs to the config and load bots that way
```
localMode:
enable: true
botIds:
- 0xabcdef1...
- 0xabcdef2...
botImages:
- my-local-test-bot-image-reference
- disco.forta.network/bafybeie5xvbbvhlrollwfb3xd4qxs5qw6rhk52ukeq2zbek6tetryqdn5a # remote image
```

Add local ability to load bots by bot ID

---

cmd/scanner/main.go
config/config.go
go.mod
go.sum

Using new "safe offset"s in block feeds whenever
- Proxy API URL is set and it is different than scan API URL
- `advanced.safeOffset` is true in `config.yml` (force-enabling)
This allows stability in scanning with multiple providers in exchange of a minor drop in SLA score.

Use the safe offset in block feed when required

---

cmd/inspector/main.go
config/config.go
go.mod
go.sum
services/inspector/inspector.go
services/supervisor/start.go

- Use the new registry inspection so the nodes, which cannot read from the registry well, have a low score
- Avoid panic in reading the assignment hash
- Use Ankr Polygon as the default JSON-RPC API for the registry

Avoid forta-scanner container crashes during assignment checks

---

store/registry.go

Alert API authorization mechanism already has protection against unregistered or disabled nodes. In other sense, batches or alerts from disabled nodes will not be accepted, so checking for the scanner's `enabled` status on scan nodes only prevents them from running bots when they are disabled but doesn't add any more security coverage.
IMHO, to mitigate any risks coming with an arbitrary redundant contract interaction, we should disable this check and let the disabled nodes do whatever they want. Besides, in an ideal world dispatch contract should return 0 assigned bots for disabled nodes anyways.

remove enabled check from registry store

---

clients/messaging/client.go
clients/messaging/subjects.go
go.mod
go.sum
services/scanner/agentpool/agent_pool.go
services/scanner/agentpool/agent_pool_test.go
services/scanner/agentpool/poolagent/agent.go
services/scanner/combiner_analyzer.go
services/scanner/combiner_stream.go
store/registry.go
tests/e2e/e2e_forta_local_mode_test.go
tests/e2e/e2e_suite_test.go
testutils/graphql-api/main.go

e2e test improvement:
handle alert test now deploys 2 bots with same image, one treated as "having a data fee subscription", and the other does not.
dispatch changes:
handle alert events now has the subscriber(target) information to prevent unauthorized bots from accessing alert data

Improve combiner dispatch authorization

---

metrics/agent_metrics.go
services/scanner/agentpool/agent_pool_test.go
services/scanner/agentpool/poolagent/agent.go

A metric `agent.start` will be published whenever a bot is being initialized by the supervisor

submit metrics on bot restarts

---

cmd/scanner/main.go
config/config.go
go.mod
go.sum
services/public-api/public_api_proxy.go
tests/e2e/e2e_forta_local_mode_test.go
testutils/graphql-api/main.go

Default query interval for alert fetching in combiner feed is 1 minute and not configurable, making tests take too longs and even timeout in certain cases. This pr makes the interval configurable

Improve handle alert e2e tests

---

services/registry/registry.go
services/registry/registry_test.go

This publishes the bot list for every iteration of the registry service to be more tolerant to missed messages.

Always publish latest bots

---

services/scanner/agentpool/agent_pool.go
services/scanner/agentpool/poolagent/agent.go

Bot version update handler wasn't updating the manifest of a deployed bot, which causes scan nodes to submit incorrect bot manifest information for the alert, even though it is executing the correct manifest version.
Sets `AgentConfig.Manifest` on version updates

update bot manifest on version updates

---

services/scanner/agentpool/agent_pool.go
services/scanner/agentpool/poolagent/agent.go

After some debugging, it appeared that `handleAgentVersionsUpdate` was not releasing the mutex. This was due to the bot calling logic in `poolagent` package grabbing the `Agent`s mutex. When that is grabbed and if the bot request lags, this causes a hang in other goroutines. This is the potential root cause for two issues:
- problem in bot deployments/updates
- input backpressure and block number lag

Unblock poolagent.Agent's mutex and avoid hangs

---

services/scanner/agentpool/agent_pool.go
services/scanner/agentpool/agent_pool_test.go

- Registry sends the new list with `messaging.SubjectAgentsVersionsLatest`
- agent pool handler processes the message, then updates `ap.agents`
- sends `messaging.SubjectAgentsActionStop`, supervisor kills the container
- supervisor sends `messaging.SubjectAgentsStatusStopped` with a list of stopped bots
- agent pool iterates `ap.agents`, calls agent.Close for matching agent and removes subscriptions for that agent
The problem is that when agent pool updated the ap.agents in step 2, there won't be any matches at step 5.
We should remove subscriptions for any `agentsToStop` immediately at version update handler
Effects:
- combiner feed will continue fetching alerts for the nuked bot
- there will be public API proxy metrics because the feed keeps fetching alerts even though there are no …

Remove subscriptions from nuked bots

---

services/scanner/agentpool/agent_pool.go
services/scanner/agentpool/agent_pool_test.go
services/scanner/agentpool/poolagent/agent.go

Instead of spawn-and-wait'ing bot initializations, lifecycle is now like the following:
- call go agent.Initialize()  at handleStatusRunning
- call SetInitialized() once initialization is completed
- SendEvaluateXXX will skip if !agent.IsInitialized()
- call agent.Close() on init errors
- at some point some routine will call ap.discardAgent(agent)  because the agent will be closed
- pool will try deploying it again
- publishes the combiner subscription message in initialize method
- it used happen in handleStatusRunning, but that thing won't have the alert config from the init response anymore

Improve bot initialization

---

services/supervisor/start_agent.go

Issue:
Pool is not aware of supervisor's bot deployment failures
Fix:
Emitting `agents.status.stopped` would inform the agent pool to remove the bot from the set of known bots, which will trigger a new deployment with the next `agents.versions.latest` message

Scanner does not re deploy bots on deployment failures

---

clients/docker/client.go
services/components/containers/bot_client.go
services/supervisor/services_test.go

- Reduce the concurrent image pull workers to 1.
- Increase the pull timeout to 10 minutes.

Reduce the heat on docker image pulls

---

cmd/cli.go
cmd/cmd_status.go

The community uses `forta status --show all --format oneline` very often for troubleshooting and that's too long and confusing.
This PR introduces a new subcommand `forta status all` that does that same thing. It accepts the `--no-color` flag.

Add new 'forta status' shorthand 'forta status all'

---

services/components/botio/bot_client.go
services/components/botio/sender.go
services/components/metrics/lifecycle.go
services/components/metrics/metrics.go

Adding subscribed bot id as detail for `agent.action.subscribe` and `agent.action.unsubscribe` metrics

Add subscription info to subscription action metrics

---

clients/docker/client.go
clients/interfaces.go
clients/mocks/mock_clients.go
services/components/containers/bot_client.go
services/components/containers/bot_client_test.go
services/runner/runner.go

The method `TearDownBot` is evolved to support step 2:
Teardown lifecycle:
1. Detach networks
2. Send `SIGTERM` and wait until the container exits, with a maximum duration of 1 minute 
3. Remove container
4. Remove networks
5. Remove image

Add support for graceful bot shutdown

---

clients/agentgrpc/client.go

should check if `invokeErr` is `status.Unimplemented` instead of `err`

Fix healthcheck evaluation

---

services/publisher/publisher.go

If post batch return an error its not visible after cycle and forta-scanner crashed with log
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x1775867]
goroutine 215 [running]:
github.com/forta-network/forta-node/services/publisher.(*Publisher).publishNextBatch(0xc000026800, 0xc00c426000)
/go/app/services/publisher/publisher.go:335 +0x1ee7
github.com/forta-network/forta-node/services/publisher.(*Publisher).publishBatches(0xc000026800)
/go/app/services/publisher/publisher.go:490 +0x8d
created by github.com/forta-network/forta-node/services/publisher.(*Publisher).Start
/go/app/services/publisher/publisher.go:809 +0x97
```

fix scope of the 'err' variable

---

services/components/botio/bot_client.go

If a bot initialization failed it's can't process requests and can't be gracefully closed that leads to memory leak.

Fix memory leak on failed bot initialization

---

clients/alertapi/api.go
clients/interfaces.go
clients/mocks/mock_clients.go
go.mod
go.sum
services/publisher/publisher.go

We are deprecating receipts logic from our system so we don't need to expect them in response from alert api

Remove receipts from the publisher
